package com.example.hibernate.model;
// Generated 24 feb 2026, 16:41:25 by Hibernate Tools 6.6.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;

/**
 * Profesor generated by hbm2java
 */
@Entity
@Table(name="profesor"
    ,catalog="instituto_121_pkiguales"
)
public class Profesor  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String ape1;
     private String ape2;
     private String tipoFuncionario;
     private ContactInfo contactinfo;

    public Profesor() {
    }

	
    public Profesor(String nombre, String ape1, String ape2) {
        this.nombre = nombre;
        this.ape1 = ape1;
        this.ape2 = ape2;
    }
    public Profesor(String nombre, String ape1, String ape2, String tipoFuncionario, ContactInfo contactinfo) {
       this.nombre = nombre;
       this.ape1 = ape1;
       this.ape2 = ape2;
       this.tipoFuncionario = tipoFuncionario;
       this.contactinfo = contactinfo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false, length=255)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="ape1", nullable=false, length=255)
    public String getApe1() {
        return this.ape1;
    }
    
    public void setApe1(String ape1) {
        this.ape1 = ape1;
    }

    
    @Column(name="ape2", nullable=false, length=255)
    public String getApe2() {
        return this.ape2;
    }
    
    public void setApe2(String ape2) {
        this.ape2 = ape2;
    }

    
    @Column(name="tipoFuncionario", length=100)
    public String getTipoFuncionario() {
        return this.tipoFuncionario;
    }
    
    @Override
    public String toString() {
        return "Profesor [id=" + id + ", nombre=" + nombre + ", ape1=" + ape1 + ", ape2=" + ape2 + ", tipoFuncionario="
                + tipoFuncionario + "]";
    }


    public void setTipoFuncionario(String tipoFuncionario) {
        this.tipoFuncionario = tipoFuncionario;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="profesor")
    public ContactInfo getContactinfo() {
        return this.contactinfo;
    }
    
    public void setContactinfo(ContactInfo contactinfo) {
        this.contactinfo = contactinfo;
    }




}


